/**
 * Every number and link the page shows, in one place.
 *
 * The figures here are measured, not illustrative: the benchmark scores come from
 * docs/eval*.json in the model repository, where each one was produced by the same harness
 * on the same examples: 200 per benchmark, 250 for MMLU. If a number changes there it
 * changes here, and nowhere else.
 */

export const SITE = {
  name: "Moonfrost AI",
  tagline: "A 777M-parameter Mixture-of-Experts language model, built and trained from scratch.",
  description:
    "Moonfrost AI is a 777M-parameter Mixture-of-Experts language model built and trained " +
    "scratch for about $55: its own tokenizer, Multi-head Latent Attention, DeepSeekMoE " +
    "routing, training loop and chat server. 161M parameters active per token.",
  url: "https://moonfrost-ai.vercel.app",
  author: "Ashish Kumar",
};

export const LINKS = {
  github: "https://github.com/whoashish115/moonfrost-ai",
  site: "https://github.com/whoashish115/moonfrost-ai-site",
  instruct: "https://huggingface.co/whoashish115/Moonfrost-777M-Instruct-v2",
  instructV1: "https://huggingface.co/whoashish115/Moonfrost-777M-Instruct-v1",
  base: "https://huggingface.co/whoashish115/Moonfrost-777M",
  dataset: "https://huggingface.co/datasets/whoashish115/Moonfrost-Persona-SFT",
  collection:
    "https://huggingface.co/collections/whoashish115/moonfrost-777m-6aa67a24b82a750ffcd9ef41",
  wandb: "https://wandb.ai/whoashish115-base/moonfrost-777m",
};

export const HEADLINE_STATS = [
  { value: "777M", label: "total parameters" },
  { value: "161M", label: "active per token" },
  { value: "6B", label: "training tokens" },
  { value: "$55", label: "total cost" },
];

export const IDEAS = [
  {
    number: "01",
    title: "Multi-head Latent Attention",
    body:
      "Instead of caching a key and a value for each of fourteen heads, the input is projected " +
      "to one shared latent of 320 numbers and keys are rebuilt from it. Position rides " +
      "separately on a 32-number rotary key, because a position-rotated key cannot be " +
      "reconstructed from an unrotated latent. The cache holds 352 numbers per token instead " +
      "of 1,792.",
  },
  {
    number: "02",
    title: "DeepSeekMoE routing",
    body:
      "Every layer above the first holds 32 routed experts and one shared expert. A router " +
      "picks the top 3, the shared expert always runs, so a token passes through 4 of 33. " +
      "Seventy per cent of the parameters are idle for any given token, which is why 777M " +
      "costs about as much to run as 161M.",
  },
  {
    number: "03",
    title: "Stacked expert dispatch",
    body:
      "Experts are three stacked (32, hidden, ffn) tensors with capacity-based routing rather " +
      "than 32 modules in a Python loop, which forced a GPU synchronisation thirty-two times " +
      "per layer per step. That single change took training from 6,056 to 179,000 tokens per " +
      "second.",
  },
];

export const TRAINING_STAGES = [
  { stage: "Pretrain phase 1", minutes: 227, tokens: "2.8B", result: "val loss 3.1486" },
  { stage: "Pretrain phase 2", minutes: 340, tokens: "3.1B", result: "val loss 2.9763" },
  { stage: "Chat fine-tune", minutes: 80, tokens: "2.7B", result: "val loss 1.2484" },
];

/**
 * Five-shot, 250 examples each, every model scored by the same harness on the same items.
 *
 * Generated by training/sync_benchmarks.py from docs/eval*.json; do not edit by hand.
 * All three Moonfrost checkpoints are present so the effect of instruction tuning
 * can be read rather than assumed. Only ARC-Easy moves: 54.8, 52.4, 44.4 across the
 * base and the two tunes. Gaps under about six points are noise at this sample size.
 */
export const BENCHMARKS = {
  columns: ["Moonfrost Base", "Moonfrost Instruct v1", "Moonfrost Instruct v2", "SmolLM2-135M", "SmolLM2-360M", "Qwen2.5-0.5B"],
  rows: [
    { name: "ARC-Easy", chance: 25.0, scores: [54.8, 52.4, 44.4, 62.8, 68.4, 64.4] },
    { name: "ARC-Challenge", chance: 25.0, scores: [25.2, 24.4, 24.4, 27.6, 37.2, 34.8] },
    { name: "HellaSwag", chance: 25.0, scores: [36.0, 38.4, 37.2, 40.0, 43.6, 42.4] },
    { name: "WinoGrande", chance: 50.0, scores: [51.2, 53.2, 54.0, 54.0, 56.0, 56.8] },
    { name: "BoolQ", chance: 50.0, scores: [62.4, 61.2, 58.8, 62.0, 63.6, 65.2] },
    { name: "MMLU", chance: 25.0, scores: [28.8, 30.0, 30.8, 32.4, 36.8, 34.4] },
  ],
};

/**
 * The public artefacts, grouped by where they live. Four Hugging Face repositories, two git
 * repositories, one run log. The collection is a link on the group it summarises rather
 * than a card of its own, because it points at the same four things.
 */
export const RESOURCE_GROUPS = [
  {
    heading: "Weights and data",
    note: "Four repositories on Hugging Face, Apache 2.0.",
    all: { label: "All four as one collection", href: LINKS.collection },
    items: [
      {
        tag: "BASE",
        title: "Moonfrost-777M",
        body:
          "Pretrained weights, 6B tokens of FineWeb-Edu, validation loss 2.976. Continues " +
          "text rather than answering it. Both tunes start here.",
        href: LINKS.base,
      },
      {
        tag: "INSTRUCT",
        title: "Moonfrost-777M-Instruct-v2",
        body:
          "1.7 epochs of supervised fine-tuning including the persona set. Best validation " +
          "loss 1.2484 at step 7,800. Answers as Moonfrost and holds a thread.",
        href: LINKS.instruct,
      },
      {
        tag: "INSTRUCT",
        title: "Moonfrost-777M-Instruct-v1",
        body:
          "0.42 epochs, no identity data, validation loss 1.3251. Claims no persona, which " +
          "makes it the neutral starting point for a tune of your own.",
        href: LINKS.instructV1,
      },
      {
        tag: "DATASET",
        title: "Moonfrost-Persona-SFT",
        body:
          "140,000 generated identity conversations, 3.3% of the v2 mixture and the whole " +
          "reason v2 has a stable self-description.",
        href: LINKS.dataset,
      },
    ],
  },
  {
    heading: "Code",
    note: "Everything that produced the weights, and this page.",
    items: [
      {
        tag: "REPOSITORY",
        title: "moonfrost-ai",
        body:
          "Tokenizer, model, training loop, evaluation harness and chat server. About " +
          "6,900 lines of Python, no modelling framework above PyTorch.",
        href: LINKS.github,
      },
      {
        tag: "REPOSITORY",
        title: "moonfrost-ai-site",
        body:
          "The source for this page: Next.js, static export, every figure on it read from " +
          "one module so the page cannot disagree with itself.",
        href: LINKS.site,
      },
    ],
  },
  {
    heading: "Training record",
    note: "The runs as they happened, loss curves included.",
    items: [
      {
        tag: "LOGS",
        title: "Weights & Biases",
        body:
          "Loss, learning rate, gradient norm and throughput for both pretraining phases " +
          "and the fine-tune, replayed from the logs the runs wrote.",
        href: LINKS.wandb,
      },
    ],
  },
];

export const AUTHOR = {
  name: "Ashish Kumar",
  handle: "@whoashish115",
  profile: "https://github.com/whoashish115",
  role: "AI Systems and Research Engineer",
  // served by GitHub, so it follows the profile rather than going stale in the repository
  avatar: "https://avatars.githubusercontent.com/whoashish115",
  // `icon` names the component the dialog renders beside each label
  links: [
    { label: "GitHub", href: "https://github.com/whoashish115", icon: "github" },
    { label: "Hugging Face", href: "https://huggingface.co/whoashish115", icon: "huggingface" },
    { label: "X", href: "https://x.com/whoashish115", icon: "x" },
    { label: "Site", href: "https://moonfrost-ai.vercel.app", icon: "globe" },
    { label: "Weights & Biases", href: "https://wandb.ai/whoashish115-base", icon: "wandb" },
  ] as const,
};

/** The whole specification, as it appears in the model card. */
export const SPEC: Array<[string, string]> = [
  ["Total parameters", "777,148,032"],
  ["Active per token", "161,036,224"],
  ["Layers", "14, one dense and thirteen Mixture-of-Experts"],
  ["Hidden size / heads", "896 / 14"],
  ["Experts", "32 routed with top-3 routing, plus 1 shared"],
  ["Attention", "Multi-head Latent Attention, 320 KV latent + 32 rotary key"],
  ["KV cache per token", "352 numbers, against 1,792 for standard attention"],
  ["Context", "1,024 tokens"],
  ["Vocabulary", "32,768, byte-level BPE trained from scratch"],
  ["Pretraining", "~6B tokens of FineWeb-Edu, val loss 2.976"],
  ["Chat fine-tune", "1.7 epochs, best at step 7,800, val loss 1.2484"],
  ["Peak / min learning rate", "6e-4 / 6e-5 pretraining, 2e-4 / 2e-5 fine-tune"],
  ["Batch", "micro-batch 24, accumulation 12, 294,912 tokens per step"],
  ["Precision", "bf16 autocast with fp32 master weights"],
  ["Held-out perplexity", "51.64 on an unseen shard"],
  ["Training throughput", "179,000 tokens/second on one H100"],
  ["Inference", "16.8 tokens/second, fp32, batch 1, RTX 3050"],
  ["Compute", "1x H100, ~12 GPU-hours, about $55"],
];

/** Where each layer's parameters sit, for the share chart. */
export const PARAMETER_SHARE = [
  { part: "Routed experts", value: 543, share: 70 },
  { part: "Attention", value: 118, share: 15 },
  { part: "Shared experts + dense", value: 84, share: 11 },
  { part: "Embedding (tied)", value: 29, share: 4 },
];

/**
 * Size against text read, for the scale chart. Only models whose developer published both
 * numbers can be placed, which is why the closed frontier models are absent here.
 */
export const LANDSCAPE = [
  { name: "GPT-2", params: 1.5e9, tokens: 1e10 },
  { name: "GPT-3", params: 1.75e11, tokens: 3e11 },
  { name: "Chinchilla", params: 7e10, tokens: 1.4e12 },
  { name: "Llama 2 7B", params: 7e9, tokens: 2e12 },
  { name: "Llama 3 8B", params: 8e9, tokens: 1.5e13 },
  { name: "DeepSeek-V3", params: 6.71e11, tokens: 1.48e13 },
  { name: "SmolLM2-135M", params: 1.35e8, tokens: 2e12 },
  { name: "SmolLM2-360M", params: 3.62e8, tokens: 4e12 },
  { name: "Qwen2.5-0.5B", params: 5e8, tokens: 1.8e13 },
  { name: "Moonfrost 777M (base)", params: 7.77e8, tokens: 6e9, ours: true },
];

/**
 * MMLU for every model people know, which is the only score published widely enough to put
 * open and closed models on one axis. Figures are each developer's own five-shot number,
 * except the four marked `here`, which were measured on this machine with the same harness
 * as Moonfrost. Where the two disagree the measured one is used: Qwen2.5-0.5B publishes
 * 47.5 and scores 34.4 here, which is the size of the gap a different harness can open.
 *
 * Nothing on this list is estimated. A model whose developer has not published a score does
 * not appear, however well known it is.
 */
export const CAPABILITY: Array<{
  name: string;
  year: number;
  mmlu: number;
  open: boolean;
  here?: boolean;
  ours?: boolean;
}> = [
  { name: "o1", year: 2024, mmlu: 91.8, open: false },
  { name: "DeepSeek-R1", year: 2025, mmlu: 90.8, open: true },
  { name: "GPT-4o", year: 2024, mmlu: 88.7, open: false },
  { name: "Claude 3.5 Sonnet", year: 2024, mmlu: 88.7, open: false },
  { name: "Llama 3.1 405B", year: 2024, mmlu: 88.6, open: true },
  { name: "DeepSeek-V3", year: 2024, mmlu: 88.5, open: true },
  { name: "Claude 3 Opus", year: 2024, mmlu: 86.8, open: false },
  { name: "GPT-4", year: 2023, mmlu: 86.4, open: false },
  { name: "Qwen2.5-72B", year: 2024, mmlu: 86.1, open: true },
  { name: "Gemini 1.5 Pro", year: 2024, mmlu: 85.9, open: false },
  { name: "Llama 3.1 70B", year: 2024, mmlu: 83.6, open: true },
  { name: "Gemma 2 9B", year: 2024, mmlu: 71.3, open: true },
  { name: "Mixtral 8x7B", year: 2023, mmlu: 70.6, open: true },
  { name: "Llama 2 70B", year: 2023, mmlu: 68.9, open: true },
  { name: "Chinchilla 70B", year: 2022, mmlu: 67.5, open: false },
  { name: "Llama 3 8B", year: 2024, mmlu: 66.6, open: true },
  { name: "LLaMA 65B", year: 2023, mmlu: 63.4, open: true },
  { name: "Mistral 7B", year: 2023, mmlu: 60.1, open: true },
  { name: "SmolLM2-1.7B", year: 2024, mmlu: 51.9, open: true },
  { name: "Llama 2 7B", year: 2023, mmlu: 45.3, open: true },
  { name: "GPT-3 175B", year: 2020, mmlu: 43.9, open: false },
  { name: "SmolLM2-360M", year: 2024, mmlu: 36.8, open: true, here: true },
  { name: "Qwen2.5-0.5B", year: 2024, mmlu: 34.4, open: true, here: true },
  { name: "SmolLM2-135M", year: 2024, mmlu: 32.4, open: true, here: true },
  { name: "Moonfrost Instruct v2", year: 2026, mmlu: 30.8, open: true, here: true, ours: true },
  { name: "OLMo 7B", year: 2024, mmlu: 28.3, open: true },
  { name: "GPT-2 1.5B", year: 2019, mmlu: 26.0, open: true },
  { name: "Pythia 1.4B", year: 2023, mmlu: 25.6, open: true },
];
